import keymirror from 'keymirror';

export const PAYLOAD_TYPES = keymirror({
  MINARAI_STANDARD_REQUEST: null,
  MINARAI_STANDARD_RESPONSE_FROM_ENGINE: null,
  MINARAI_STANDARD_RESPONSE_FROM_MINARAI: null,
  ANOI_REQUEST: null,
  ANOI_RESPONSE: null,
  GODSPEED_REQUEST: null,
  GODSPEED_RESPONSE: null,
  CSCHAT_APPLICATION_SERVER_RESPONSE: null,
});

